CREATE TABLE _e.error_events (
	event_id varchar(55),
	event_name varchar(55),
	event_timestamp timestamp without time zone,
	insert_timestamp timestamp without time zone NOT NULL,
    session_id varchar(50),
    bb_device_id bigint,
    user_id bigint,
    device_id varchar(50),
    android_advertising_id varchar(50),
    client_id varchar(30),
    channel varchar(20),
    os varchar(30),
    client_type varchar(20),
    app_language varchar(20),
    app_version varchar(20),
    app_version_code varchar(20),
    current_url varchar,
    merchant_id varchar(20),
    utm_referrer varchar,
    utm_platform varchar(50),
    utm_source varchar(80),
    utm_medium varchar(80),
    utm_campaign varchar(80),
	event_params jsonb);