from sqlalchemy import ARRAY, Column, String, TIMESTAMP, Boolean, Float, BigInteger
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class InstagramAccountRequest(Base):
    __tablename__ = 'instagram_account_request'

    id = Column(BigInteger, primary_key=True)
    updated_at = Column(TIMESTAMP)
    created_at = Column(TIMESTAMP)
    handle = Column(String)
    status = Column(String)


class InstagramAccount(Base):
    __tablename__ = 'instagram_account'

    id = Column(BigInteger, primary_key=True)
    updated_at = Column(TIMESTAMP)
    created_at = Column(TIMESTAMP)
    profile_id = Column(String)
    profile_type = Column(String)
    handle = Column(String)
    biography = Column(String)
    profile_pic_url = Column(String)
    followers = Column(BigInteger)
    following = Column(BigInteger)
    media_count = Column(BigInteger)
    full_name = Column(String)
    category = Column(String)
    category_id = Column(String)
    fbid = Column(String)
    is_private = Column(Boolean)
    is_verified = Column(Boolean)
    is_business_or_creator = Column(Boolean)
    on_gcc = Column(Boolean)
    is_in_gcc_collection = Column(Boolean)
    is_creator = Column(Boolean)
    refreshed_at = Column(TIMESTAMP)
    avg_likes = Column(Float)
    avg_reach = Column(Float)
    avg_impressions = Column(Float)
    avg_engagement = Column(Float)
    avg_comments = Column(Float)
    avg_reels_plays = Column(Float)


class InstagramAccountTimeSeries(Base):
    __tablename__ = 'instagram_account_ts'

    id = Column(BigInteger, primary_key=True)
    profile_id = Column(String)
    profile_type = Column(String)
    handle = Column(String)
    biography = Column(String)
    profile_pic_url = Column(String)
    followers = Column(BigInteger)
    following = Column(BigInteger)
    media_count = Column(BigInteger)
    full_name = Column(String)
    category = Column(String)
    category_id = Column(String)
    is_private = Column(Boolean)
    is_business_or_creator = Column(Boolean)
    is_verified = Column(Boolean)
    created_at = Column(TIMESTAMP)
    fbid = Column(String)


class InstagramPost(Base):
    __tablename__ = 'instagram_post'

    id = Column(BigInteger, primary_key=True)
    handle = Column(String)
    updated_at = Column(TIMESTAMP)
    created_at = Column(TIMESTAMP)
    profile_id = Column(String)
    post_id = Column(String)
    post_type = Column(String)
    content_type = Column(String)
    shortcode = Column(String)
    likes = Column(BigInteger)
    comments = Column(BigInteger)
    views = Column(BigInteger)
    plays = Column(BigInteger)
    reach = Column(BigInteger)
    shares = Column(BigInteger)
    saved = Column(BigInteger)
    impressions = Column(BigInteger)
    interactions = Column(BigInteger)
    engagement = Column(Float)
    caption = Column(String)
    display_url = Column(String)
    publish_time = Column(TIMESTAMP)
    thumbnail_url = Column(String)
    taps_forward = Column(BigInteger)
    taps_back = Column(BigInteger)
    exits = Column(BigInteger)
    automatic_forward = Column(BigInteger)
    swipe_back = Column(BigInteger)
    swipe_forward = Column(BigInteger)
    swipe_up = Column(BigInteger)
    swipe_down = Column(BigInteger)
    replies = Column(BigInteger)
    navigation = Column(BigInteger)
    profile_activity = Column(BigInteger)
    profile_visits = Column(BigInteger)
    follows = Column(BigInteger)
    video_views = Column(BigInteger)
    story_links=Column(ARRAY(String))
    story_hashtags=Column(ARRAY(String))
    keywords = Column(String)
    profile_follower = Column(BigInteger)
    profile_er = Column(Float)
    profile_static_er = Column(Float)
    profile_reels_er = Column(Float)


class InstagramPostTimeSeries(Base):
    __tablename__ = 'instagram_post_ts'

    id = Column(BigInteger, primary_key=True)
    handle = Column(String)
    created_at = Column(TIMESTAMP)
    profile_id = Column(String)
    post_id = Column(String)
    post_type = Column(String)
    content_type = Column(String)
    shortcode = Column(String)
    likes = Column(BigInteger)
    comments = Column(BigInteger)
    views = Column(BigInteger)
    plays = Column(BigInteger)
    reach = Column(BigInteger)
    shares = Column(BigInteger)
    saved = Column(BigInteger)
    impressions = Column(BigInteger)
    interactions = Column(BigInteger)
    engagement = Column(Float)
    caption = Column(String)
    display_url = Column(String)
    thumbnail_url = Column(String)
    publish_time = Column(TIMESTAMP)
    taps_forward = Column(BigInteger)
    taps_back = Column(BigInteger)
    exits = Column(BigInteger)
    # automatic_forward = Column(BigInteger)
    # swipe_back = Column(BigInteger)
    # swipe_forward = Column(BigInteger)
    # swipe_up = Column(BigInteger)
    # swipe_down = Column(BigInteger)
    replies = Column(BigInteger)
    navigation = Column(BigInteger)
    profile_activity = Column(BigInteger)
    profile_visits = Column(BigInteger)
    follows = Column(BigInteger)
    video_views = Column(BigInteger)

class InstagramProfileInsights(Base):
    __tablename__ = 'instagram_profile_insights'
    
    id = Column(BigInteger, primary_key=True)
    profile_id = Column(String)
    handle = Column(String)
    created_at = Column(TIMESTAMP)
    updated_at = Column(TIMESTAMP)
    audience_country = Column(JSONB)
    audience_city = Column(JSONB)
    audience_gender_age = Column(JSONB)
    audience_locale = Column(JSONB)
    reached_audience_country = Column(JSONB)
    reached_audience_city = Column(JSONB)
    reached_audience_gender_age = Column(JSONB)
    engaged_audience_country = Column(JSONB)
    engaged_audience_city = Column(JSONB)
    engaged_audience_gender_age = Column(JSONB)
