{{ config(materialized = 'table', tags=["daily", "leaderboard"], order_by='month, platform, platform_id') }}
select
	month,
	'IA' profile_platform,
	language,
	category,
	ifNull(platform, 'MISSING') platform,
	platform_id,
	followers,
	engagement_rate,
	avg_likes,
	avg_comments,
	avg_views,
	avg_plays,
	followers_rank,
	followers_change_rank,
	views_rank,
	followers_rank_by_cat,
	views_rank_by_cat,
	followers_rank_by_lang,
	views_rank_by_lang,
	followers_rank_by_cat_lang,
	views_rank_by_cat_lang,
	country,
	profile_type,
	views,
	0 prev_views,
	ia_views,
	yt_views,
	uploads,
	prev_followers,
	followers_change,
	likes,
	comments,
	plays,
	prev_plays,
	engagement,
	followers_change_rank_by_cat_lang,
	plays_rank,
	plays_rank_by_cat,
	plays_rank_by_lang,
	plays_rank_by_cat_lang,
	followers_change_rank_by_cat,
	followers_change_rank_by_lang,
	CAST(map(
        'followers_rank', ifNull(followers_rank_prev, 0),
        'views_rank', ifNull(views_rank_prev, 0),
        'followers_change_rank', ifNull(followers_change_rank_prev, 0),
        'plays_rank', ifNull(plays_rank_prev, 0),
        'followers_rank_by_cat', ifNull(followers_rank_by_cat_prev, 0),
        'views_rank_by_cat', ifNull(views_rank_by_cat_prev, 0),
        'followers_change_rank_by_cat', ifNull(followers_change_rank_by_cat_prev, 0),
        'plays_rank_by_cat', ifNull(plays_rank_by_cat_prev, 0),
        'followers_rank_by_lang', ifNull(followers_rank_by_lang_prev, 0),
        'views_rank_by_lang', ifNull(views_rank_by_lang_prev, 0),
        'followers_change_rank_by_lang', ifNull(followers_change_rank_by_lang_prev, 0),
        'plays_rank_by_lang', ifNull(plays_rank_by_lang_prev, 0),
        'followers_rank_by_cat_lang', ifNull(followers_rank_by_cat_lang_prev, 0),
        'views_rank_by_cat_lang', ifNull(views_rank_by_cat_lang_prev, 0),
        'followers_change_rank_by_cat_lang', ifNull(followers_change_rank_by_cat_lang_prev, 0),
        'plays_rank_by_cat_lang', ifNull(plays_rank_by_cat_lang_prev, 0),
		'plays_rank_by_cat_profile', ifNull(plays_rank_by_cat_profile_prev, 0),
		'views_rank_by_cat_profile', ifNull(views_rank_by_cat_profile_prev, 0),
		'followers_change_rank_by_cat_profile', ifNull(followers_change_rank_by_cat_profile_prev, 0),
		'followers_rank_by_cat_profile', ifNull(followers_rank_by_cat_profile_prev, 0),
		'plays_rank_by_lang_profile', ifNull(plays_rank_by_lang_profile_prev, 0),
		'views_rank_by_lang_profile', ifNull(views_rank_by_lang_profile_prev, 0),
		'followers_change_rank_by_lang_profile', ifNull(followers_change_rank_by_lang_profile_prev, 0),
		'followers_rank_by_lang_profile', ifNull(followers_rank_by_lang_profile_prev, 0),
		'plays_rank_by_profile', ifNull(plays_rank_by_profile_prev, 0),
		'views_rank_by_profile', ifNull(views_rank_by_profile_prev, 0),
		'followers_change_rank_by_profile', ifNull(followers_change_rank_by_profile_prev, 0),
		'followers_rank_by_profile', ifNull(followers_rank_by_profile_prev, 0),
		'plays_rank_by_cat_lang_profile', ifNull(plays_rank_by_cat_lang_profile_prev, 0),
		'views_rank_by_cat_lang_profile', ifNull(views_rank_by_cat_lang_profile_prev, 0),
		'followers_change_rank_by_cat_lang_profile', ifNull(followers_change_rank_by_cat_lang_profile_prev, 0),
		'followers_rank_by_cat_lang_profile', ifNull(followers_rank_by_cat_lang_profile_prev, 0)
    ), 'Map(String, UInt64)') last_month_ranks,
	CAST(map(
        'followers_rank', ifNull(followers_rank, 0),
        'views_rank', ifNull(views_rank, 0),
        'followers_change_rank', ifNull(followers_change_rank, 0),
        'plays_rank', ifNull(plays_rank, 0),
        'followers_rank_by_cat', ifNull(followers_rank_by_cat, 0),
        'views_rank_by_cat', ifNull(views_rank_by_cat, 0),
        'followers_change_rank_by_cat', ifNull(followers_change_rank_by_cat, 0),
        'plays_rank_by_cat', ifNull(plays_rank_by_cat, 0),
        'followers_rank_by_lang', ifNull(followers_rank_by_lang, 0),
        'views_rank_by_lang', ifNull(views_rank_by_lang, 0),
        'followers_change_rank_by_lang', ifNull(followers_change_rank_by_lang, 0),
        'plays_rank_by_lang', ifNull(plays_rank_by_lang, 0),
        'followers_rank_by_cat_lang', ifNull(followers_rank_by_cat_lang, 0),
        'views_rank_by_cat_lang', ifNull(views_rank_by_cat_lang, 0),
        'followers_change_rank_by_cat_lang', ifNull(followers_change_rank_by_cat_lang, 0),
        'plays_rank_by_cat_lang', ifNull(plays_rank_by_cat_lang, 0),
		'plays_rank_by_cat_profile', ifNull(plays_rank_by_cat_profile, 0),
		'views_rank_by_cat_profile', ifNull(views_rank_by_cat_profile, 0),
		'followers_change_rank_by_cat_profile', ifNull(followers_change_rank_by_cat_profile, 0),
		'followers_rank_by_cat_profile', ifNull(followers_rank_by_cat_profile, 0),
		'plays_rank_by_lang_profile', ifNull(plays_rank_by_lang_profile, 0),
		'views_rank_by_lang_profile', ifNull(views_rank_by_lang_profile, 0),
		'followers_change_rank_by_lang_profile', ifNull(followers_change_rank_by_lang_profile, 0),
		'followers_rank_by_lang_profile', ifNull(followers_rank_by_lang_profile, 0),
		'plays_rank_by_profile', ifNull(plays_rank_by_profile, 0),
		'views_rank_by_profile', ifNull(views_rank_by_profile, 0),
		'followers_change_rank_by_profile', ifNull(followers_change_rank_by_profile, 0),
		'followers_rank_by_profile', ifNull(followers_rank_by_profile, 0),
		'plays_rank_by_cat_lang_profile', ifNull(plays_rank_by_cat_lang_profile, 0),
		'views_rank_by_cat_lang_profile', ifNull(views_rank_by_cat_lang_profile, 0),
		'followers_change_rank_by_cat_lang_profile', ifNull(followers_change_rank_by_cat_lang_profile, 0),
		'followers_rank_by_cat_lang_profile', ifNull(followers_rank_by_cat_lang_profile, 0)
    ), 'Map(String, UInt64)') current_month_ranks
from {{ref('mart_instagram_leaderboard')}}

UNION ALL

select
	month,
	'YA' profile_platform,
	language,
	category,
	ifNull(platform, 'MISSING') platform,
	platform_id,
	followers,
	engagement_rate,
	avg_likes,
	avg_comments,
	avg_views,
	0 avg_plays,
	followers_rank,
	followers_change_rank,
	views_rank,
	followers_rank_by_cat,
	views_rank_by_cat,
	followers_rank_by_lang,
	views_rank_by_lang,
	followers_rank_by_cat_lang,
	views_rank_by_cat_lang,
	country,
	profile_type,
	views,
	prev_views,
	ia_views,
	yt_views,
	uploads,
	prev_followers,
	followers_change,
	likes,
	comments,
	0 plays,
	0 prev_plays,
	engagement,
	followers_change_rank_by_cat_lang,
	0 plays_rank,
	0 plays_rank_by_cat,
	0 plays_rank_by_lang,
	0 plays_rank_by_cat_lang,
	followers_change_rank_by_cat,
	followers_change_rank_by_lang,
	CAST(map(
        'followers_rank', ifNull(followers_rank_prev, 0),
        'views_rank', ifNull(views_rank_prev, 0),
        'followers_change_rank', ifNull(followers_change_rank_prev, 0),
        'plays_rank', 0,
        'followers_rank_by_cat', ifNull(followers_rank_by_cat_prev, 0),
        'views_rank_by_cat', ifNull(views_rank_by_cat_prev, 0),
        'followers_change_rank_by_cat', ifNull(followers_change_rank_by_cat_prev, 0),
        'plays_rank_by_cat', 0,
        'followers_rank_by_lang', ifNull(followers_rank_by_lang_prev, 0),
        'views_rank_by_lang', ifNull(views_rank_by_lang_prev, 0),
        'followers_change_rank_by_lang', ifNull(followers_change_rank_by_lang_prev, 0),
        'plays_rank_by_lang', 0,
        'followers_rank_by_cat_lang', ifNull(followers_rank_by_cat_lang_prev, 0),
        'views_rank_by_cat_lang', ifNull(views_rank_by_cat_lang_prev, 0),
        'followers_change_rank_by_cat_lang', ifNull(followers_change_rank_by_cat_lang_prev, 0),
        'plays_rank_by_cat_lang', 0,
		'plays_rank_by_cat_profile', 0,
		'views_rank_by_cat_profile', ifNull(views_rank_by_cat_profile_prev, 0),
		'followers_change_rank_by_cat_profile', ifNull(followers_change_rank_by_cat_profile_prev, 0),
		'followers_rank_by_cat_profile', ifNull(followers_rank_by_cat_profile_prev, 0),
		'plays_rank_by_lang_profile', 0,
		'views_rank_by_lang_profile', ifNull(views_rank_by_lang_profile_prev, 0),
		'followers_change_rank_by_lang_profile', ifNull(followers_change_rank_by_lang_profile_prev, 0),
		'followers_rank_by_lang_profile', ifNull(followers_rank_by_lang_profile_prev, 0),
		'plays_rank_by_profile', 0,
		'views_rank_by_profile', ifNull(views_rank_by_profile_prev, 0),
		'followers_change_rank_by_profile', ifNull(followers_change_rank_by_profile_prev, 0),
		'followers_rank_by_profile', ifNull(followers_rank_by_profile_prev, 0),
		'plays_rank_by_cat_lang_profile', 0,
		'views_rank_by_cat_lang_profile', ifNull(views_rank_by_cat_lang_profile_prev, 0),
		'followers_change_rank_by_cat_lang_profile', ifNull(followers_change_rank_by_cat_lang_profile_prev, 0),
		'followers_rank_by_cat_lang_profile', ifNull(followers_rank_by_cat_lang_profile_prev, 0)
    ), 'Map(String, UInt64)') last_month_ranks,
	CAST(map(
        'followers_rank', ifNull(followers_rank, 0),
        'views_rank', ifNull(views_rank, 0),
        'followers_change_rank', ifNull(followers_change_rank, 0),
        'plays_rank', 0,
        'followers_rank_by_cat', ifNull(followers_rank_by_cat, 0),
        'views_rank_by_cat', ifNull(views_rank_by_cat, 0),
        'followers_change_rank_by_cat', ifNull(followers_change_rank_by_cat, 0),
        'plays_rank_by_cat', 0,
        'followers_rank_by_lang', ifNull(followers_rank_by_lang, 0),
        'views_rank_by_lang', ifNull(views_rank_by_lang, 0),
        'followers_change_rank_by_lang', ifNull(followers_change_rank_by_lang, 0),
        'plays_rank_by_lang', 0,
        'followers_rank_by_cat_lang', ifNull(followers_rank_by_cat_lang, 0),
        'views_rank_by_cat_lang', ifNull(views_rank_by_cat_lang, 0),
        'followers_change_rank_by_cat_lang', ifNull(followers_change_rank_by_cat_lang, 0),
        'plays_rank_by_cat_lang', 0,
		'plays_rank_by_cat_profile', 0,
		'views_rank_by_cat_profile', ifNull(views_rank_by_cat_profile, 0),
		'followers_change_rank_by_cat_profile', ifNull(followers_change_rank_by_cat_profile, 0),
		'followers_rank_by_cat_profile', ifNull(followers_rank_by_cat_profile, 0),
		'plays_rank_by_lang_profile', 0,
		'views_rank_by_lang_profile', ifNull(views_rank_by_lang_profile, 0),
		'followers_change_rank_by_lang_profile', ifNull(followers_change_rank_by_lang_profile, 0),
		'followers_rank_by_lang_profile', ifNull(followers_rank_by_lang_profile, 0),
		'plays_rank_by_profile', 0,
		'views_rank_by_profile', ifNull(views_rank_by_profile, 0),
		'followers_change_rank_by_profile', ifNull(followers_change_rank_by_profile, 0),
		'followers_rank_by_profile', ifNull(followers_rank_by_profile, 0),
		'plays_rank_by_cat_lang_profile', 0,
		'views_rank_by_cat_lang_profile', ifNull(views_rank_by_cat_lang_profile, 0),
		'followers_change_rank_by_cat_lang_profile', ifNull(followers_change_rank_by_cat_lang_profile, 0),
		'followers_rank_by_cat_lang_profile', ifNull(followers_rank_by_cat_lang_profile, 0)
    ), 'Map(String, UInt64)') current_month_ranks
from {{ref('mart_youtube_leaderboard')}}

UNION ALL

select
	month,
	profile_platform,
	language,
	category,
	ifNull(platform, 'MISSING') platform,
	platform_id,
	followers,
	engagement_rate,
	avg_likes,
	avg_comments,
	avg_views,
	0 avg_plays,
	followers_rank,
	followers_change_rank,
	views_rank,
	followers_rank_by_cat,
	views_rank_by_cat,
	followers_rank_by_lang,
	views_rank_by_lang,
	followers_rank_by_cat_lang,
	views_rank_by_cat_lang,
	country,
	profile_type,
	views,
	prev_views,
	ia_views,
	yt_views,
	uploads,
	prev_followers,
	followers_change,
	likes,
	comments,
	0 plays,
	0 prev_plays,
	engagement,
	followers_change_rank_by_cat_lang,
	0 plays_rank,
	0 plays_rank_by_cat,
	0 plays_rank_by_lang,
	0 plays_rank_by_cat_lang,
	followers_change_rank_by_cat,
	followers_change_rank_by_lang,
	CAST(map(
        'followers_rank', ifNull(followers_rank_prev,0),
        'views_rank', ifNull(views_rank_prev, 0),
        'followers_change_rank', ifNull(followers_change_rank_prev, 0),
        'plays_rank', 0,
        'followers_rank_by_cat', ifNull(followers_rank_by_cat_prev, 0),
        'views_rank_by_cat', ifNull(views_rank_by_cat_prev, 0),
        'followers_change_rank_by_cat', ifNull(followers_change_rank_by_cat_prev, 0),
        'plays_rank_by_cat', 0,
        'followers_rank_by_lang', ifNull(followers_rank_by_lang_prev, 0),
        'views_rank_by_lang', ifNull(views_rank_by_lang_prev, 0),
        'followers_change_rank_by_lang', ifNull(followers_change_rank_by_lang_prev, 0),
        'plays_rank_by_lang', 0,
        'followers_rank_by_cat_lang', ifNull(followers_rank_by_cat_lang_prev, 0),
        'views_rank_by_cat_lang', ifNull(views_rank_by_cat_lang_prev, 0),
        'followers_change_rank_by_cat_lang', ifNull(followers_change_rank_by_cat_lang_prev, 0),
        'plays_rank_by_cat_lang', 0,
		'plays_rank_by_cat_profile', 0,
		'views_rank_by_cat_profile', ifNull(views_rank_by_cat_profile_prev, 0),
		'followers_change_rank_by_cat_profile', ifNull(followers_change_rank_by_cat_profile_prev, 0),
		'followers_rank_by_cat_profile', ifNull(followers_rank_by_cat_profile_prev, 0),
		'plays_rank_by_lang_profile', 0,
		'views_rank_by_lang_profile', ifNull(views_rank_by_lang_profile_prev, 0),
		'followers_change_rank_by_lang_profile', ifNull(followers_change_rank_by_lang_profile_prev, 0),
		'followers_rank_by_lang_profile', ifNull(followers_rank_by_lang_profile_prev, 0),
		'plays_rank_by_profile', 0,
		'views_rank_by_profile', ifNull(views_rank_by_profile_prev, 0),
		'followers_change_rank_by_profile', ifNull(followers_change_rank_by_profile_prev, 0),
		'followers_rank_by_profile', ifNull(followers_rank_by_profile_prev, 0),
		'plays_rank_by_cat_lang_profile', 0,
		'views_rank_by_cat_lang_profile', ifNull(views_rank_by_cat_lang_profile_prev, 0),
		'followers_change_rank_by_cat_lang_profile', ifNull(followers_change_rank_by_cat_lang_profile_prev, 0),
		'followers_rank_by_cat_lang_profile', ifNull(followers_rank_by_cat_lang_profile_prev, 0)
    ), 'Map(String, UInt64)') last_month_ranks,
	CAST(map(
        'followers_rank', ifNull(followers_rank,0),
        'views_rank', ifNull(views_rank, 0),
        'followers_change_rank', ifNull(followers_change_rank, 0),
        'plays_rank', 0,
        'followers_rank_by_cat', ifNull(followers_rank_by_cat, 0),
        'views_rank_by_cat', ifNull(views_rank_by_cat, 0),
        'followers_change_rank_by_cat', ifNull(followers_change_rank_by_cat, 0),
        'plays_rank_by_cat', 0,
        'followers_rank_by_lang', ifNull(followers_rank_by_lang, 0),
        'views_rank_by_lang', ifNull(views_rank_by_lang, 0),
        'followers_change_rank_by_lang', ifNull(followers_change_rank_by_lang, 0),
        'plays_rank_by_lang', 0,
        'followers_rank_by_cat_lang', ifNull(followers_rank_by_cat_lang, 0),
        'views_rank_by_cat_lang', ifNull(views_rank_by_cat_lang, 0),
        'followers_change_rank_by_cat_lang', ifNull(followers_change_rank_by_cat_lang, 0),
        'plays_rank_by_cat_lang', 0,
		'plays_rank_by_cat_profile', 0,
		'views_rank_by_cat_profile', ifNull(views_rank_by_cat_profile, 0),
		'followers_change_rank_by_cat_profile', ifNull(followers_change_rank_by_cat_profile, 0),
		'followers_rank_by_cat_profile', ifNull(followers_rank_by_cat_profile, 0),
		'plays_rank_by_lang_profile', 0,
		'views_rank_by_lang_profile', ifNull(views_rank_by_lang_profile, 0),
		'followers_change_rank_by_lang_profile', ifNull(followers_change_rank_by_lang_profile, 0),
		'followers_rank_by_lang_profile', ifNull(followers_rank_by_lang_profile, 0),
		'plays_rank_by_profile', 0,
		'views_rank_by_profile', ifNull(views_rank_by_profile, 0),
		'followers_change_rank_by_profile', ifNull(followers_change_rank_by_profile, 0),
		'followers_rank_by_profile', ifNull(followers_rank_by_profile, 0),
		'plays_rank_by_cat_lang_profile', 0,
		'views_rank_by_cat_lang_profile', ifNull(views_rank_by_cat_lang_profile, 0),
		'followers_change_rank_by_cat_lang_profile', ifNull(followers_change_rank_by_cat_lang_profile, 0),
		'followers_rank_by_cat_lang_profile', ifNull(followers_rank_by_cat_lang_profile, 0)
    ), 'Map(String, UInt64)') current_month_ranks
from {{ref('mart_cross_platform_leaderboard')}}
SETTINGS max_bytes_before_external_group_by = 20000000000, max_bytes_before_external_sort = 20000000000, join_algorithm='partial_merge'
