package header

// common custom header names
const (
	Authorization string = "Authorization"
	ForwardedFor  string = "x-forwarded-for"
	UID           string = "x-bb-uid"
	Timestamp     string = "x-bb-timestamp"
	Os            string = "x-bb-os"
	ClientID      string = "x-bb-clientid"
	RequestID     string = "x-bb-requestid"
	ClientType    string = "x-bb-clienttype"
	Version       string = "x-bb-version"
	VersionName   string = "x-bb-version-name"
	Latitude      string = "x-bb-latitude"
	Longitude     string = "x-bb-longitude"
	Location      string = "x-bb-location"
	Device        string = "x-bb-deviceid"
	BBDevice      string = "x-bb-custom-deviceid"
	Channel       string = "x-bb-channelid"
	Country       string = "x-bb-country"
	Locale        string = "accept-language"
	ApolloOpName  string = "x-apollo-operation-name"
	ApolloOpID    string = "x-apollo-operation-id"
	UserRT        string = "x-bb-user-rt"
	AdvertisingID string = "x-bb-advertising-id"
	ABTestInfo    string = "x-ab-test-info"
	RemoteConfig  string = "fb-remote-config"
	XRetryCount   string = "x-retry-count"
	RobotsTag     string = "X-Robots-Tag"
	SellerId      string = "X-bb-sellerid"
	PpId          string = "X-bb-ppid"
	WebengageApp  string = "x-bb-webengage-app"
)
