{{ config(materialized = 'table') }}
with gpt_data as (select handle,
                         JSONExtractString(dimensions, 'city')            city_,
                         if(city_ in ('Unknown', 'UNKNOWN'), '', city_)   city,
                         if(city LIKE '%[%', arrayMap(x -> replaceAll(x, '\"', ''), JSONExtractArrayRaw(city)),
                            splitByString('/', city))     as              cities,
                         cities[1]                                        primary_city,
                         JSONExtractString(dimensions, 'state')           state_,
                         if(state_ in ('Unknown', 'UNKNOWN'), '', state_) state,
                         if(state LIKE '%[%', arrayMap(x -> replaceAll(x, '\"', ''), JSONExtractArrayRaw(state)),
                            splitByString('/', state))    as              states,
                         states[1]                                        primary_state,
                         JSONExtractString(dimensions, 'country')         country_,
                         if(country_ in
                            ('Unknown', 'UNKNOWN', 'NA', 'Not Available', 'Around the world', 'Bikini Bottom', 'Earth',
                             'Global', 'GLOBAL', 'INTERNATIONAL', 'International', 'Middle East',
                             'Middle East and North Africa', 'Multiple', 'Online', 'Somewhere in the world', 'World',
                             'Worldwide', 'Various'), '',
                            country_)                                     country,
                         IF(country LIKE '%[%',
                            arrayMap(x -> replaceAll(x, '\"', ''), JSONExtractArrayRaw(country)),
                            arrayMap(x -> trim(both ' ' from x),
                                     splitByString('/', replaceAll(replaceAll(country, ',', '|'), '|', '/')))
                         )                                as              countries,
                         countries[1]                                     primary_country,
                         JSONExtractString(dimensions, 'languages')       languages_,
                         if(languages_ in ('Unknown', 'UNKNOWN', 'Not specified'), '',
                            languages_)                                   language,
                         if(language LIKE '%[%', arrayMap(x -> replaceAll(x, '\"', ''), JSONExtractArrayRaw(language)),
                            splitByString('/', language)) as              languages,
                         languages[1]                                     primary_language,
                         JSONExtractString(dimensions, 'gender')          gender,
                         if(gender not in ('FEMALE', 'MALE'), '', gender) gender_
                  from _e.profile_log_events
                  where source = 'openapi_profile_info_v0.12')
   , final as (select handle,
                      if(toString(primary_city) in ('Unknown', 'UNKNOWN', 'NA', 'Not Available', 'Not specified'), '',
                         primary_city)                           city,
                      if(city = '', [], cities)                  cities,
                      if(toString(primary_state) in ('Unknown', 'UNKNOWN', 'NA', 'Not Available', 'Not specified'), '',
                         primary_state)                          state,
                      if(state = '', [], states)                 states,
                      if(toString(primary_country) in ('Unknown', 'UNKNOWN', 'NA', 'Not Available', 'Not specified'),
                         '', primary_country)                    country_name,
                      if(country_name = '', [], countries)              countries,
                      if(toString(primary_language) in ('Unknown', 'UNKNOWN', 'NA', 'Not Available', 'Not specified'),
                         '', primary_language)                   language_name,
                      multiIf(lower(language_name) = 'english', 'en', lower(language_name) = 'assaamese', 'as', lower(language_name) = 'manipuri', 'mni', lower(language_name) = 'bodo', 'brx', lower(language_name) = 'nagamese', 'nag', lower(language_name) = 'bhojpuri', 'bho', lower(language_name) = 'rajasthani', 'raj', lower(language_name) = 'nepali', 'ne', lower(language_name) = 'khasi', 'kha', lower(language_name) = 'mizo', 'lus',lower(language_name) = 'urdu', 'ur', lower(language_name) = 'hindi', 'hi', lower(language_name) = 'bengali', 'bn', lower(language_name) = 'tamil', 'ta', lower(language_name) = 'telugu', 'te', lower(language_name) = 'malayalam', 'ml', lower(language_name) = 'marathi', 'mr', lower(language_name) = 'kannada', 'ka', lower(language_name) = 'gujarati', 'gu', lower(language_name) = 'punjabi', 'pa', lower(language_name) = 'odia', 'or', NULL) language_code,
                      if(toString(language_name) = '', [], languages) languages,
                      gender_                                    gender
               from gpt_data)
select handle,
       city,
       cities,
       state,
       states,
       country_name,
       mcc.code country,
       countries,
       language_name,
       language_code as language,
       languages,
       gender
from final
         left join dbt.mart_country_codes mcc on mcc.name = country_name