from instagram.entities.entities import InstagramAccount, InstagramAccountTimeSeries, InstagramPost, InstagramPostTimeSeries, InstagramProfileInsights
from instagram.metric_dim_store import AUDIENCE_COUNTRY, ENGAGED_AUDIENCE_CITY, ENGAGED_AUDIENCE_COUNTRY, ENGAGED_AUDIENCE_GENDER_AGE, KEYWORDS, MEDIA_COUNT, FOLLOWERS, FOLLOWING, PROFILE_ER, PROFILE_FOLLOWER, PROFILE_ID, PROFILE_PIC, BIO, \
    IS_VERIFIED, IS_PRIVATE, CATEGORY, CATEGORY_ID, FBID, FULL_NAME, COMMENTS, LIKES, DISPLAY_URL, POST_TYPE, PROFILE_REELS_ER, PROFILE_STATIC_ER, \
    PUBLISH_TIME, CAPTION, HANDLE, AUTOMATIC_FORWARD, REACHED_AUDIENCE_CITY, REACHED_AUDIENCE_GENDER_AGE, STORY_HASHTAGS, STORY_LINKS, SWIPE_BACK, SWIPE_DOWN, SWIPE_FORWARD, SWIPE_UP, TAP_BACK, TAP_EXIT, TAP_FORWARD, VIEW_COUNT, PLAY_COUNT, POST_ID, PROFILE_TYPE, THUMBNAIL, IS_BUSINESS_OR_CREATOR, \
    REACH, IMPRESSIONS, ENGAGEMENT, SAVED, SHARES, INTERACTIONS, AUDIENCE_CITY, AUDIENCE_GENDER_AGE, AUDIENCE_LOCALE, \
    REPLIES, NAVIGATION, PROFILE_VISITS, PROFILE_ACTIVITY, FOLLOWS, \
    CONTENT_TYPE, VIDEO_VIEWS, REACHED_AUDIENCE_COUNTRY
"""
    Map scrapper keys to entity keys
"""
profile_map = {
    BIO: InstagramAccount.biography.name, 
    CATEGORY_ID: InstagramAccount.category_id.name,
    CATEGORY: InstagramAccount.category.name, 
    FBID: InstagramAccount.fbid.name, 
    FOLLOWERS: InstagramAccount.followers.name, 
    FOLLOWING: InstagramAccount.following.name, 
    FULL_NAME: InstagramAccount.full_name.name, 
    HANDLE: InstagramAccount.handle.name,
    IS_BUSINESS_OR_CREATOR: InstagramAccount.is_business_or_creator.name,
    IS_PRIVATE: InstagramAccount.is_private.name, 
    IS_VERIFIED: InstagramAccount.is_verified.name, 
    MEDIA_COUNT: InstagramAccount.media_count.name, 
    PROFILE_ID: InstagramAccount.profile_id.name, 
    PROFILE_PIC: InstagramAccount.profile_pic_url.name, 
    PROFILE_TYPE: InstagramAccount.profile_type.name,
}

profile_map_ts = {
    BIO: InstagramAccountTimeSeries.biography.name, 
    CATEGORY_ID: InstagramAccountTimeSeries.category_id.name,
    CATEGORY: InstagramAccountTimeSeries.category.name, 
    FBID: InstagramAccountTimeSeries.fbid.name, 
    FOLLOWERS: InstagramAccountTimeSeries.followers.name, 
    FOLLOWING: InstagramAccountTimeSeries.following.name, 
    FULL_NAME: InstagramAccountTimeSeries.full_name.name, 
    HANDLE: InstagramAccountTimeSeries.handle.name,
    IS_BUSINESS_OR_CREATOR: InstagramAccountTimeSeries.is_business_or_creator.name,
    IS_PRIVATE: InstagramAccountTimeSeries.is_private.name, 
    IS_VERIFIED: InstagramAccountTimeSeries.is_verified.name, 
    MEDIA_COUNT: InstagramAccountTimeSeries.media_count.name, 
    PROFILE_ID: InstagramAccountTimeSeries.profile_id.name, 
    PROFILE_PIC: InstagramAccountTimeSeries.profile_pic_url.name, 
    PROFILE_TYPE: InstagramAccountTimeSeries.profile_type.name,
}

profile_insights_map = {
    PROFILE_ID: InstagramProfileInsights.profile_id.name,
    HANDLE: InstagramProfileInsights.handle.name,
    AUDIENCE_COUNTRY: InstagramProfileInsights.audience_country.name,
    AUDIENCE_CITY: InstagramProfileInsights.audience_city.name,
    AUDIENCE_GENDER_AGE: InstagramProfileInsights.audience_gender_age.name,
    AUDIENCE_LOCALE: InstagramProfileInsights.audience_locale.name,
    REACHED_AUDIENCE_COUNTRY: InstagramProfileInsights.reached_audience_country.name,
    REACHED_AUDIENCE_CITY: InstagramProfileInsights.reached_audience_city.name,
    REACHED_AUDIENCE_GENDER_AGE: InstagramProfileInsights.reached_audience_gender_age.name,
    ENGAGED_AUDIENCE_COUNTRY: InstagramProfileInsights.engaged_audience_country.name,
    ENGAGED_AUDIENCE_CITY: InstagramProfileInsights.engaged_audience_city.name,
    ENGAGED_AUDIENCE_GENDER_AGE: InstagramProfileInsights.engaged_audience_gender_age.name,
    
}

post_map = {
    CAPTION: InstagramPost.caption.name, 
    COMMENTS: InstagramPost.comments.name, 
    DISPLAY_URL: InstagramPost.display_url.name, 
    ENGAGEMENT: InstagramPost.engagement.name,
    HANDLE: InstagramPost.handle.name,
    IMPRESSIONS: InstagramPost.impressions.name,
    INTERACTIONS: InstagramPost.interactions.name,
    LIKES: InstagramPost.likes.name, 
    PLAY_COUNT: InstagramPost.plays.name, 
    POST_ID: InstagramPost.post_id.name, 
    POST_TYPE: InstagramPost.post_type.name, 
    PROFILE_ID: InstagramPost.profile_id.name, 
    PUBLISH_TIME: InstagramPost.publish_time.name,
    REACH: InstagramPost.reach.name,
    SAVED: InstagramPost.saved.name,
    SHARES: InstagramPost.shares.name,
    THUMBNAIL: InstagramPost.thumbnail_url.name,
    VIEW_COUNT: InstagramPost.views.name,
    TAP_FORWARD: InstagramPost.taps_forward.name,
    TAP_BACK: InstagramPost.taps_back.name,
    TAP_EXIT: InstagramPost.exits.name,
    AUTOMATIC_FORWARD : InstagramPost.automatic_forward.name,
    SWIPE_BACK : InstagramPost.swipe_back.name,
    SWIPE_FORWARD : InstagramPost.swipe_forward.name,
    SWIPE_UP : InstagramPost.swipe_up.name,
    SWIPE_DOWN: InstagramPost.swipe_down.name,
    REPLIES: InstagramPost.replies.name,
    NAVIGATION: InstagramPost.navigation.name,
    PROFILE_ACTIVITY: InstagramPost.profile_activity.name,
    PROFILE_VISITS: InstagramPost.profile_visits.name,
    FOLLOWS: InstagramPost.follows.name,
    CONTENT_TYPE: InstagramPost.content_type.name,
    VIDEO_VIEWS: InstagramPost.video_views.name,
    STORY_LINKS: InstagramPost.story_links.name,
    STORY_HASHTAGS: InstagramPost.story_hashtags.name,
    KEYWORDS: InstagramPost.keywords.name,
    PROFILE_FOLLOWER: InstagramPost.profile_follower.name,
    PROFILE_ER: InstagramPost.profile_er.name,
    PROFILE_STATIC_ER: InstagramPost.profile_static_er.name,
    PROFILE_REELS_ER: InstagramPost.profile_reels_er.name
}

# post_map_ts = {
#     CAPTION: InstagramPostTimeSeries.caption.name, 
#     COMMENTS: InstagramPostTimeSeries.comments.name, 
#     DISPLAY_URL: InstagramPostTimeSeries.display_url.name,
#     ENGAGEMENT: InstagramPostTimeSeries.engagement.name, 
#     HANDLE: InstagramPostTimeSeries.handle.name,
#     IMPRESSIONS: InstagramPostTimeSeries.impressions.name,
#     INTERACTIONS: InstagramPostTimeSeries.interactions.name,
#     LIKES: InstagramPostTimeSeries.likes.name, 
#     PLAY_COUNT: InstagramPostTimeSeries.plays.name, 
#     POST_ID: InstagramPostTimeSeries.post_id.name, 
#     POST_TYPE: InstagramPostTimeSeries.post_type.name, 
#     PROFILE_ID: InstagramPostTimeSeries.profile_id.name, 
#     PUBLISH_TIME: InstagramPostTimeSeries.publish_time.name,
#     REACH: InstagramPostTimeSeries.reach.name,
#     SAVED: InstagramPostTimeSeries.saved.name,
#     SHARES: InstagramPostTimeSeries.shares.name,
#     THUMBNAIL: InstagramPostTimeSeries.thumbnail_url.name,
#     VIEW_COUNT: InstagramPostTimeSeries.views.name,
#     REPLIES: InstagramPost.replies.name,
#     NAVIGATION: InstagramPost.navigation.name,
#     PROFILE_ACTIVITY: InstagramPost.profile_activity.name,
#     PROFILE_VISITS: InstagramPost.profile_visits.name,
#     FOLLOWS: InstagramPost.follows.name,
#     CONTENT_TYPE: InstagramPost.content_type.name,
#     VIDEO_VIEWS: InstagramPost.video_views.name,
#     TAP_FORWARD: InstagramPost.taps_forward.name,
#     TAP_BACK: InstagramPost.taps_back.name,
#     TAP_EXIT: InstagramPost.exits.name,
#     AUTOMATIC_FORWARD : InstagramPost.automatic_forward.name,
#     SWIPE_BACK : InstagramPost.swipe_back.name,
#     SWIPE_FORWARD : InstagramPost.swipe_forward.name,
#     SWIPE_UP : InstagramPost.swipe_up.name,
#     SWIPE_DOWN: InstagramPost.swipe_down.name,
# }
