{{ config(materialized = 'table', tags=["staging_collections"], order_by='collection_id, post_short_code') }}
with
_from_collection as (
    select
        platform,
        post_collection_id collection_id,
        mia.ig_id profile_social_id,
        item.short_code post_short_code,
        item.post_type post_type,
        '' post_title,
        post_link,
        post_thumbnail,
        [] hashtags,
        [] keywords,
        item.id post_collection_item_id,
        item.created_at published_at,
        'POST' collection_type,
        posted_by_handle profile_handle,
        posted_by_handle profile_name,
        mia.followers followers,
        0 views,
        0 likes,
        0 comments,
        0 impressions,
        0 saves,
        0 plays,
        round((-0.000025017) * mia.followers + (1.11 * (mia.followers * abs(log2(mia.engagement_rate * 100)) * 2 / 100))) _story_reach,
        if(item.post_type = 'story', _story_reach, 0) reach,
        0 swipe_ups,
        0 mentions,
        0 sticker_taps,
        0 shares,
        0 story_exits,
        0 story_back_taps,
        0 story_forward_taps,
        0 link_clicks,
        0 orders,
        0 total_engagement,
        total_engagement / reach engagement_rate,
        replace(JSONExtractArrayRaw(ifNull(item.sponsor_links, '[]'))[1], '"', '') link
    from {{ref('stg_coffee_staging_post_collection_item')}} item
    left join dbt.mart_instagram_account mia on mia.handle = item.posted_by_handle
    where item.platform = 'INSTAGRAM'
),
urls as (
    select link from _from_collection
    group by link
),
link_clicks as (
    select concat('https://', url) link, sum(unique_clicks) clicks
    from dbt.mart_link_clicks
    where concat('https://', url) in urls
    group by link
),
link_orders as (
    select concat('https://', link) url,
           sum(overall_orders) all_orders,
           sum(delivered_orders) delivered_orders,
           sum(completed_orders) completed_orders,
           sum(leaderboard_overall_orders) leaderboard_overall_orders,
           sum(leaderboard_delivered_orders) leaderboard_delivered_orders,
           sum(leaderboard_completed_orders) leaderboard_completed_orders
    from dbt.mart_link_clicks_orders
    where concat('https://', link)  in urls
    group by url
),
from_collection as (
    select
        platform,
        collection_id,
        profile_social_id,
        post_short_code,
        post_type,
        post_title,
        post_link,
        post_thumbnail,
        hashtags,
        keywords,
        post_collection_item_id,
        published_at,
        collection_type,
        profile_handle,
        profile_name,
        followers,
        views,
        likes,
        comments,
        impressions,
        saves,
        plays,
        reach,
        swipe_ups,
        mentions,
        sticker_taps,
        shares,
        story_exits,
        story_back_taps,
        story_forward_taps,
        lc.clicks link_clicks,
        lo.all_orders orders,
        lo.delivered_orders delivered_orders,
        lo.completed_orders completed_orders,
        lo.leaderboard_overall_orders leaderboard_overall_orders,
        lo.leaderboard_delivered_orders leaderboard_delivered_orders,
        lo.leaderboard_completed_orders leaderboard_completed_orders,
        total_engagement,
        engagement_rate
    from _from_collection base
    left join link_orders lo on lo.url = base.link
    left join link_clicks lc on lc.link = base.link
),
from_ts as (
    select
        platform,
        collection_id,
        profile_social_id,
        post_short_code,
        max(post_type) post_type,
        max(post_title) post_title,
        max(post_link) post_link,
        max(post_thumbnail) post_thumbnail,
        max(hashtags) hashtags,
        max(keywords) keywords,
        max(post_collection_item_id) post_collection_item_id,
        max(published_at) published_at,
        max(collection_type) collection_type,
        max(profile_handle) profile_handle,
        max(profile_name) profile_name,
        max(followers) followers,
        max(views) views,
        max(likes) likes,
        max(comments) comments,
        max(impressions) impressions,
        max(saves) saves,
        max(plays) plays,
        max(reach) reach,
        max(swipe_ups) swipe_ups,
        max(mentions) mentions,
        max(sticker_taps) sticker_taps,
        max(shares) shares,
        max(story_exits) story_exits,
        max(story_back_taps) story_back_taps,
        max(story_forward_taps) story_forward_taps,
        max(link_clicks) link_clicks,
        max(orders) orders,
        max(delivered_orders) delivered_orders,
        max(completed_orders) completed_orders,
        max(leaderboard_overall_orders) leaderboard_overall_orders,
        max(leaderboard_delivered_orders) leaderboard_delivered_orders,
        max(leaderboard_completed_orders) leaderboard_completed_orders,
        max(total_engagement) total_engagement,
        total_engagement / reach engagement_rate
    from {{ref('mart_staging_collection_post_ts')}}
    group by platform, collection_id, profile_social_id, post_short_code
),
all as (
    select
        platform,
        collection_id,
        profile_social_id,
        post_short_code,
        post_type,
        post_title,
        post_link,
        post_thumbnail,
        hashtags,
        keywords,
        post_collection_item_id,
        published_at,
        collection_type,
        profile_handle,
        profile_name,
        followers,
        views,
        likes,
        comments,
        impressions,
        saves,
        plays,
        reach,
        swipe_ups,
        mentions,
        sticker_taps,
        shares,
        story_exits,
        story_back_taps,
        story_forward_taps,
        link_clicks,
        orders,
        delivered_orders,
        completed_orders,
        leaderboard_overall_orders,
        leaderboard_delivered_orders,
        leaderboard_completed_orders,
        total_engagement,
        engagement_rate
    from from_collection
    union all
    select
        platform,
        collection_id,
        profile_social_id,
        post_short_code,
        post_type,
        post_title,
        post_link,
        post_thumbnail,
        hashtags,
        keywords,
        post_collection_item_id,
        published_at,
        collection_type,
        profile_handle,
        profile_name,
        followers,
        views,
        likes,
        comments,
        impressions,
        saves,
        plays,
        reach,
        swipe_ups,
        mentions,
        sticker_taps,
        shares,
        story_exits,
        story_back_taps,
        story_forward_taps,
        link_clicks,
        orders,
        delivered_orders,
        completed_orders,
        leaderboard_overall_orders,
        leaderboard_delivered_orders,
        leaderboard_completed_orders,
        total_engagement,
        engagement_rate
    from from_ts
),
final as (
    select
        platform,
        collection_id,
        post_short_code,
        max(profile_social_id) profile_social_id,
        max(post_type) post_type,
        max(post_title) post_title,
        max(post_link) post_link,
        max(post_thumbnail) post_thumbnail,
        max(hashtags) hashtags,
        max(keywords) keywords,
        max(post_collection_item_id) post_collection_item_id,
        max(published_at) published_at,
        max(collection_type) collection_type,
        max(profile_handle) profile_handle,
        max(profile_name) profile_name,
        max(followers) followers,
        max(views) views,
        max(likes) likes,
        max(comments) comments,
        max(impressions) impressions,
        max(saves) saves,
        max(plays) plays,
        max(reach) reach,
        max(swipe_ups) swipe_ups,
        max(mentions) mentions,
        max(sticker_taps) sticker_taps,
        max(shares) shares,
        max(story_exits) story_exits,
        max(story_back_taps) story_back_taps,
        max(story_forward_taps) story_forward_taps,
        max(link_clicks) link_clicks,
        max(orders) orders,
        max(delivered_orders) delivered_orders,
        max(completed_orders) completed_orders,
        max(leaderboard_overall_orders) leaderboard_overall_orders,
        max(leaderboard_delivered_orders) leaderboard_delivered_orders,
        max(leaderboard_completed_orders) leaderboard_completed_orders,
        max(total_engagement) total_engagement,
        max(engagement_rate) engagement_rate
    from all
    group by platform, collection_id, post_short_code
)
select * from final
SETTINGS max_bytes_before_external_group_by = 20000000000, max_bytes_before_external_sort = 20000000000, join_algorithm='partial_merge'
