with
instagram_age_gender_groups as (
    select
        handle,
        profile_id,
        audience_gender_age         aga,
        JSONExtractString(aga, 'male')   male,
        JSONExtractString(aga, 'female') female,
        JSONExtractString(aga, 'uncategorized') uncategorized,
        JSONExtractFloat(male, '65+')      m_65,
        JSONExtractFloat(male, '13-17')    m_13_17,
        JSONExtractFloat(male, '18-24')    m_18_24,
        JSONExtractFloat(male, '25-34')    m_25_34,
        JSONExtractFloat(male, '35-44')    m_35_44,
        JSONExtractFloat(male, '45-54')    m_45_54,
        JSONExtractFloat(male, '55-64')    m_55_64,
        JSONExtractFloat(female, '65+')    f_65,
        JSONExtractFloat(female, '13-17')  f_13_17,
        JSONExtractFloat(female, '18-24')  f_18_24,
        JSONExtractFloat(female, '25-34')  f_25_34,
        JSONExtractFloat(female, '35-44')  f_35_44,
        JSONExtractFloat(female, '45-54')  f_45_54,
        JSONExtractFloat(female, '55-64')  f_55_64,
        m_13_17 + m_18_24 + m_25_34 + m_35_44 + m_45_54 + m_55_64 + m_65 male_total,
        f_13_17 + f_18_24 + f_25_34 + f_35_44 + f_45_54 + f_55_64 + f_65 female_total,
        male_total+female_total total,
        round((male_total/total)*100, 2) male_followers_perc,
        round((female_total/total)*100, 2) female_followers_perc,
        round((m_13_17/total)*100, 2) m_13_17_perc, round((m_18_24/total)*100, 2) m_18_24_perc,
        round((m_25_34/total)*100, 2) m_25_34_perc, round((m_35_44/total)*100, 2) m_35_44_perc,
        round((m_45_54/total)*100, 2) m_45_54_perc, round((m_55_64/total)*100, 2) m_55_64_perc,
        round((m_65/total)*100, 2) m_65_perc,
        round((f_13_17/total)*100, 2) f_13_17_perc, round((f_18_24/total)*100, 2) f_18_24_perc,
        round((f_25_34/total)*100, 2) f_25_34_perc, round((f_35_44/total)*100, 2) f_35_44_perc,
        round((f_45_54/total)*100, 2) f_45_54_perc, round((f_55_64/total)*100, 2) f_55_64_perc,
        round((f_65/total)*100, 2) f_65_perc
    from dbt.stg_beat_instagram_profile_insights),
instagram_age_gender_data as (
    select
        handle,
        profile_id,
		if(isNaN(male_followers_perc), 0, male_followers_perc) AS male_followers_perc,
    	if(isNaN(female_followers_perc), 0, female_followers_perc) AS female_followers_perc,
        ['M_13-17', 'M_18-24', 'M_25-34', 'M_35-44', 'M_45-54', 'M_55-64', 'M_65+', 'F_13-17', 'F_18-24', 'F_25-34', 'F_35-44', 'F_45-54', 'F_55-64', 'F_65+'] age_groups,
        arrayMap(x -> if(isNaN(ifNull(x, 0)), 0, ifNull(x, 0)),
        [m_13_17_perc, m_18_24_perc, m_25_34_perc, m_35_44_perc, m_45_54_perc, m_55_64_perc, m_65_perc,
        f_13_17_perc, f_18_24_perc, f_25_34_perc, f_35_44_perc, f_45_54_perc, f_55_64_perc, f_65_perc]) AS age_groups_percs
    from instagram_age_gender_groups),
instagram_city_data AS (
    SELECT
        handle,
        profile_id,
        IFNULL(audience_city, '{}') AS ac,
        JSONExtractKeysAndValues(ac, 'Int64') AS keys_values,
        arrayStringConcat(keys_values, ',') as joined,
        arrayMap(x -> lowerUTF8(splitByString(',', x.1)[1]), keys_values) AS city_list,
        arrayMap(x -> x.2, keys_values) AS values_array,
        arraySum(arrayMap(x -> x.2, keys_values)) AS total_value_sum,
    	arrayMap(x -> round((x / total_value_sum)*100, 2), arrayMap(x -> x.2, keys_values)) AS city_percs
    FROM dbt.stg_beat_instagram_profile_insights
),
instagram_data as (
    select
        'INSTAGRAM' platform,
        ifNull(iagd.profile_id, 'MISSING') platform_id,
        iagd.handle platform_handle,
        0 reachable_followers_perc,
        0 audience_authenticity,
        0 breakup_low_followers,
        0 breakup_high_following,
        0 breakup_audience_authenticity,
        '' breakup_audience_authenticity_grade,
        '' breakup_high_following_grade,
        '' breakup_low_followers_grade,
        '' breakup_followers_growth30d_grade,
        '' breakup_views_30d_grade,
        '' breakup_uploads_30d_grade,
        0 audience_quality_score,
        '' audience_quality_grade,
        iagd.male_followers_perc male_followers_perc,
        iagd.female_followers_perc female_followers_perc,
        ['0'] notable_followers,
        iagd.age_groups age_groups,
        iagd.age_groups_percs age_group_percs,
        icd.city_list cities,
        icd.city_percs city_percs,
        ['IN'] countries,
        [1.0] country_percs
    from instagram_age_gender_data iagd
    inner join instagram_city_data icd on icd.profile_id = iagd.profile_id
),
youtube_age_gender_groups as (
    select
        id,
        channel_id,
        gender_age         aga,
        JSONExtractString(aga, 'male')   male,
        JSONExtractString(aga, 'female') female,
        JSONExtractString(aga, 'uncategorized') uncategorized,
        JSONExtractFloat(male, 'age65-')      m_65,
        JSONExtractFloat(male, 'age13-17')    m_13_17,
        JSONExtractFloat(male, 'age18-24')    m_18_24,
        JSONExtractFloat(male, 'age25-34')    m_25_34,
        JSONExtractFloat(male, 'age35-44')    m_35_44,
        JSONExtractFloat(male, 'age45-54')    m_45_54,
        JSONExtractFloat(male, 'age55-64')    m_55_64,
        JSONExtractFloat(female, 'age65-')    f_65,
        JSONExtractFloat(female, 'age13-17')  f_13_17,
        JSONExtractFloat(female, 'age18-24')  f_18_24,
        JSONExtractFloat(female, 'age25-34')  f_25_34,
        JSONExtractFloat(female, 'age35-44')  f_35_44,
        JSONExtractFloat(female, 'age45-54')  f_45_54,
        JSONExtractFloat(female, 'age55-64')  f_55_64,
        m_13_17 + m_18_24 + m_25_34 + m_35_44 + m_45_54 + m_55_64 + m_65 male_total,
        f_13_17 + f_18_24 + f_25_34 + f_35_44 + f_45_54 + f_55_64 + f_65 female_total,
        male_total+female_total total,
        round((male_total/total)*100, 2) male_followers_perc,
        round((female_total/total)*100, 2) female_followers_perc,
        round((m_13_17/total)*100, 2) m_13_17_perc, round((m_18_24/total)*100, 2) m_18_24_perc,
        round((m_25_34/total)*100, 2) m_25_34_perc, round((m_35_44/total)*100, 2) m_35_44_perc,
        round((m_45_54/total)*100, 2) m_45_54_perc, round((m_55_64/total)*100, 2) m_55_64_perc,
        round((m_65/total)*100, 2) m_65_perc,
        round((f_13_17/total)*100, 2) f_13_17_perc, round((f_18_24/total)*100, 2) f_18_24_perc,
        round((f_25_34/total)*100, 2) f_25_34_perc, round((f_35_44/total)*100, 2) f_35_44_perc,
        round((f_45_54/total)*100, 2) f_45_54_perc, round((f_55_64/total)*100, 2) f_55_64_perc,
        round((f_65/total)*100, 2) f_65_perc
    from dbt.stg_beat_youtube_profile_insights),
youtube_age_gender_data as (
    SELECT
    id,
    channel_id,
    if(isNaN(male_followers_perc), 0, male_followers_perc) AS male_followers_perc,
    if(isNaN(female_followers_perc), 0, female_followers_perc) AS female_followers_perc,
    ['M_13-17', 'M_18-24', 'M_25-34', 'M_35-44', 'M_45-54', 'M_55-64', 'M_65+',
    'F_13-17', 'F_18-24', 'F_25-34', 'F_35-44', 'F_45-54', 'F_55-64', 'F_65+'] AS age_groups,
    arrayMap(x -> if(isNaN(ifNull(x, 0)), 0, ifNull(x, 0)),
        [m_13_17_perc, m_18_24_perc, m_25_34_perc, m_35_44_perc, m_45_54_perc, m_55_64_perc, m_65_perc,
        f_13_17_perc, f_18_24_perc, f_25_34_perc, f_35_44_perc, f_45_54_perc, f_55_64_perc, f_65_perc]) AS age_groups_percs
	FROM youtube_age_gender_groups),
youtube_city_data AS (
    SELECT
        id,
        channel_id,
	    city ac1,
	    IFNULL(city, '{}') AS ac,
        JSONExtractKeysAndValuesRaw(ac) AS keys_values_raw,
        arrayFilter(x -> x.2 != '0', JSONExtractKeysAndValuesRaw(ac)) AS key_values_modified,
        arrayMap(x -> x.1, arrayFilter(x -> match(x.1, '^[a-zA-Z]+$'), key_values_modified)) AS city_list,
	    arrayMap(x -> x.2, arrayFilter(x -> match(x.1, '^[a-zA-Z]+$'), key_values_modified)) AS filtered_values,
	    arraySum(arrayMap(x -> toInt64(x), filtered_values)) AS total_sum_of_values,
	    if(total_sum_of_values = 0, [], arrayMap(x -> round((toInt64(x) / total_sum_of_values)*100, 2), filtered_values)) AS city_percs
    FROM dbt.stg_beat_youtube_profile_insights
),
youtube_data as (
    select
        'YOUTUBE' platform,
        ifNull(channel_id, 'MISSING') platform_id,
        channel_id platform_handle,
        0 reachable_followers_perc,
        0 audience_authenticity,
        0 breakup_low_followers,
        0 breakup_high_following,
        0 breakup_audience_authenticity,
        '' breakup_audience_authenticity_grade,
        '' breakup_high_following_grade,
        '' breakup_low_followers_grade,
        '' breakup_followers_growth30d_grade,
        '' breakup_views_30d_grade,
        '' breakup_uploads_30d_grade,
        0 audience_quality_score,
        '' audience_quality_grade,
        yagd.male_followers_perc male_followers_perc,
        yagd.female_followers_perc female_followers_perc,
        ['0'] notable_followers,
        yagd.age_groups age_groups,
        yagd.age_groups_percs age_group_percs,
        ycd.city_list cities,
        ycd.city_percs city_percs,
        ['IN'] countries,
        [1.0] country_percs
    from youtube_age_gender_data yagd
    left join youtube_city_data ycd on ycd.channel_id = yagd.channel_id
)
select * from instagram_data union all select * from youtube_data
