gcc_social:
  target: production
  outputs:
    production:
      type: postgres
      schema: public
      host: 172.31.2.21
      port: 5432
      database: beat
      user: postgres
      password: VeryStronkPazswordfortheGCcDb12217
      threads: 6

gcc_warehouse:
  target: production
  outputs:
    production:
      type: clickhouse
      schema: dbt
      host: 172.31.28.68
      port: 9000
      user: airflow
      password: 9yO32wh02zv99
      threads: 3
